# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build do
 # sync_code_signing
  #disable_automatic_code_signing(path: "TestForFastLane.xcodeproj")
  build_app(scheme: "TestForFastLane",
         	  workspace: "TestForFastLane.xcworkspace",
		  export_method: "ad-hoc",
                  include_bitcode: true)
  #enable_automatic_code_signing(path: "TestForFastLane.xcodeproj")


	
  end
end
